print("Enter your name- ")
n = input()
print("Hello, " + n)
print("Where are you from,- ")
h = input()
print("So who is the current governor of " + h )
g = input()
print("What do you do for fun")
f = input()
print( f + " sounds childish. Don't you have any other hobbies?")
